"""Embed Pagefind's binary assets into a fetch-intercepting JS shim.

Pagefind powers Starlight's search bar via a Web Worker that fetches WASM,
metadata, index shards, and result fragments over the network. Most browsers
block `fetch()` from `file://` URLs, which breaks search when the dist is
double-clicked offline.

This script generates two files in `dist/pagefind/`:

  _offline-data.js   — base64 map of every binary pagefind asset
  _offline-patch.js  — installs a `fetch()` interceptor on `self` that serves
                       those assets directly in both main-thread and worker
                       contexts

It then prepends `importScripts()` calls to `pagefind-worker.js` so the worker
loads both files before Pagefind's own code runs.

The HTML injection (adding <script> tags to every page before the search UI
loads) is handled by offline-fixup.py, which runs after this script via the
`postbuild` npm hook.
"""
from __future__ import annotations

import base64
import json
from pathlib import Path

DIST = Path(__file__).resolve().parent.parent / "dist"
PAGEFIND = DIST / "pagefind"

# Binary asset globs — everything the Pagefind runtime fetches at search time.
ASSET_GLOBS = [
    "*.pf_meta",
    "wasm.*.pagefind",
    "pagefind-entry.json",
    "fragment/*.pf_fragment",
    "index/*.pf_index",
]


def collect_assets() -> dict[str, str]:
    """Return a map: "/pagefind/<relpath>" -> base64-encoded file contents."""
    assets: dict[str, str] = {}
    for pattern in ASSET_GLOBS:
        for path in PAGEFIND.glob(pattern):
            rel = path.relative_to(DIST).as_posix()
            key = "/" + rel
            assets[key] = base64.b64encode(path.read_bytes()).decode("ascii")
    return assets


PATCH_JS = r"""// Pagefind offline fetch interceptor.
// Runs in both main-thread (window) and worker (self) contexts.
// Serves preloaded binary assets from window.__PAGEFIND_OFFLINE__ when the
// fetched URL ends with a known /pagefind/... suffix.
(function () {
  var ctx = (typeof self !== 'undefined') ? self : (typeof window !== 'undefined' ? window : null);
  if (!ctx) return;
  var data = ctx.__PAGEFIND_OFFLINE__;
  if (!data) return;
  if (ctx.__PAGEFIND_OFFLINE_PATCHED__) return;
  ctx.__PAGEFIND_OFFLINE_PATCHED__ = true;

  function base64ToBytes(b64) {
    var bin = atob(b64);
    var len = bin.length;
    var bytes = new Uint8Array(len);
    for (var i = 0; i < len; i++) bytes[i] = bin.charCodeAt(i);
    return bytes;
  }

  function contentTypeFor(key) {
    if (key.endsWith('.json')) return 'application/json';
    if (key.endsWith('.pagefind')) return 'application/wasm';
    return 'application/octet-stream';
  }

  function lookup(url) {
    var u = String(url).split('?')[0].split('#')[0];
    var keys = Object.keys(data);
    for (var i = 0; i < keys.length; i++) {
      if (u.endsWith(keys[i])) return { key: keys[i], b64: data[keys[i]] };
    }
    return null;
  }

  var realFetch = ctx.fetch ? ctx.fetch.bind(ctx) : null;
  ctx.fetch = function (input, init) {
    var url = (input && input.url) ? input.url : input;
    var hit = lookup(url);
    if (hit) {
      var bytes = base64ToBytes(hit.b64);
      return Promise.resolve(new Response(bytes, {
        status: 200,
        headers: { 'Content-Type': contentTypeFor(hit.key) }
      }));
    }
    if (realFetch) return realFetch(input, init);
    return Promise.reject(new Error('fetch unavailable and no offline match for ' + url));
  };
})();
"""


def write_data_js(assets: dict[str, str]) -> Path:
    out = PAGEFIND / "_offline-data.js"
    # Use JSON-in-JS for a compact, correct literal.
    payload = json.dumps(assets, separators=(",", ":"))
    body = (
        "// Auto-generated by tools/offline-pagefind.py — do not edit.\n"
        "var ctx=(typeof self!=='undefined')?self:(typeof window!=='undefined'?window:this);\n"
        f"ctx.__PAGEFIND_OFFLINE__={payload};\n"
    )
    out.write_text(body, encoding="utf-8")
    return out


def write_patch_js() -> Path:
    out = PAGEFIND / "_offline-patch.js"
    out.write_text("// Auto-generated by tools/offline-pagefind.py — do not edit.\n" + PATCH_JS, encoding="utf-8")
    return out


def patch_worker() -> bool:
    """Prepend importScripts() calls to pagefind-worker.js.

    The worker runs in its own global scope and must load the data + patch
    before Pagefind's worker code starts calling fetch.
    """
    worker = PAGEFIND / "pagefind-worker.js"
    if not worker.is_file():
        return False
    text = worker.read_text(encoding="utf-8")
    marker = "/* __pagefind_offline_worker_shim__ */"
    if marker in text:
        return True
    shim = (
        f"{marker}\n"
        "try { importScripts('./_offline-data.js'); } catch (e) {}\n"
        "try { importScripts('./_offline-patch.js'); } catch (e) {}\n"
    )
    worker.write_text(shim + text, encoding="utf-8")
    return True


def main() -> None:
    if not PAGEFIND.is_dir():
        raise SystemExit(f"{PAGEFIND} not found — run `astro build` first")
    assets = collect_assets()
    if not assets:
        raise SystemExit(f"no binary pagefind assets found under {PAGEFIND}")
    total_bytes = sum(len(v) for v in assets.values())
    data_path = write_data_js(assets)
    patch_path = write_patch_js()
    worker_patched = patch_worker()
    print(
        f"offline-pagefind: embedded {len(assets)} assets "
        f"({total_bytes // 1024} KiB base64) into {data_path.name}, "
        f"patch={patch_path.name}, worker_shim={'yes' if worker_patched else 'skipped'}"
    )


if __name__ == "__main__":
    main()
